<?php
add_action('init', function () {
	register_post_type('employer', array(
		'labels' => array(
			'name' => 'Employers',
			'singular_name' => 'Employer',
			'menu_name' => 'Employers',
			'all_items' => 'All Employers',
			'edit_item' => 'Edit Employer',
			'view_item' => 'View Employer',
			'view_items' => 'View Employers',
			'add_new_item' => 'Add New Employer',
			'new_item' => 'New Employer',
			'parent_item_colon' => 'Parent Employer:',
			'search_items' => 'Search Employers',
			'not_found' => 'No employers found',
			'not_found_in_trash' => 'No employers found in Trash',
			'archives' => 'Employer Archives',
			'attributes' => 'Employer Attributes',
			'insert_into_item' => 'Insert into employer',
			'uploaded_to_this_item' => 'Uploaded to this employer',
			'filter_items_list' => 'Filter employers list',
			'filter_by_date' => 'Filter employers by date',
			'items_list_navigation' => 'Employers list navigation',
			'items_list' => 'Employers list',
			'item_published' => 'Employer published.',
			'item_published_privately' => 'Employer published privately.',
			'item_reverted_to_draft' => 'Employer reverted to draft.',
			'item_scheduled' => 'Employer scheduled.',
			'item_updated' => 'Employer updated.',
			'item_link' => 'Employer Link',
			'item_link_description' => 'A link to a employer.',
		),
		'public' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'employer',
		'graphql_plural_name' => 'employers',
		'menu_icon' => 'dashicons-businessperson',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'delete_with_user' => false,
	));
});
