<?php
add_action('init', function () {
	register_post_type('skill', array(
		'labels' => array(
			'name' => 'Skills',
			'singular_name' => 'Skill',
			'menu_name' => 'Skills',
			'all_items' => 'All Skills',
			'edit_item' => 'Edit Skill',
			'view_item' => 'View Skill',
			'view_items' => 'View Skills',
			'add_new_item' => 'Add New Skill',
			'new_item' => 'New Skill',
			'parent_item_colon' => 'Parent Skill:',
			'search_items' => 'Search Skills',
			'not_found' => 'No skills found',
			'not_found_in_trash' => 'No skills found in Trash',
			'archives' => 'Skill Archives',
			'attributes' => 'Skill Attributes',
			'insert_into_item' => 'Insert into skill',
			'uploaded_to_this_item' => 'Uploaded to this skill',
			'filter_items_list' => 'Filter skills list',
			'filter_by_date' => 'Filter skills by date',
			'items_list_navigation' => 'Skills list navigation',
			'items_list' => 'Skills list',
			'item_published' => 'Skill published.',
			'item_published_privately' => 'Skill published privately.',
			'item_reverted_to_draft' => 'Skill reverted to draft.',
			'item_scheduled' => 'Skill scheduled.',
			'item_updated' => 'Skill updated.',
			'item_link' => 'Skill Link',
			'item_link_description' => 'A link to a skill.',
		),
		'public' => true,
		'hierarchical' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'skill',
		'graphql_plural_name' => 'skills',
		'menu_icon' => 'dashicons-hammer',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'has_archive' => 'skills',
		'rewrite' => array(
			'feeds' => false,
		),
		'delete_with_user' => false,
	));
});
